openapi: 3.0.3
info:
  title: Bema Hub API
  description: API specification for the Bema Hub platform
  version: 0.1.0

servers:
  - url: https://www.bemahub.local/wp-json
    description: Development server

paths:
  /wp/v2/users:
    get:
      summary: Retrieve users
      description: Get a list of users from the WordPress database
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the user
        name:
          type: string
          description: Display name for the user
        email:
          type: string
          format: email
          description: The user's email address
      required:
        - id
        - name
        - email