import {Geist, Geist_Mono, Inter, Poppins} from "next/font/google";
import "./globals.css";
import Header from "@/component/header";
import HeroSection from "@/component/HeroSection";
import PlatformSection from "@/component/PlatformSection";
import InsightsSection from "@/component/InsightSection";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const inter = Inter({
    subsets: ["Latin"],
    variable: "--font-inter",
    display: "swap",
});

const poppins = Poppins({
    subsets: ["Latin"],
    variable: "--font-poppins",
    weight: ["600", "700", "800"],
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable}  ${inter.variable} ${poppins.variable} antialiased`}
            suppressHydrationWarning
        >
        <Header/>
        <HeroSection/>
        <PlatformSection/>
        <InsightsSection/>
        <main>{children}</main>
        </body>
        </html>
    );
}
